name: aaj_kya_banaye_admin
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-151.0.dev <4.0.0'

dependencies:
  card_swiper: ^2.0.4
  cloud_firestore: ^4.4.3
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  firebase_storage: ^11.0.14
  flutter:
    sdk: flutter
  flutter_image_compress: ^1.1.3
  image_cropper: ^3.0.1
  image_picker: ^0.8.6+3
  photofilters: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
