// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBugyNQse3FRCBnDp02yQyE73fFbZ5y4Qk',
    appId: '1:89201019839:web:d259296be761142068af0a',
    messagingSenderId: '89201019839',
    projectId: 'aaj-kya-banaye-5d8a4',
    authDomain: 'aaj-kya-banaye-5d8a4.firebaseapp.com',
    storageBucket: 'aaj-kya-banaye-5d8a4.appspot.com',
    measurementId: 'G-QVEXQ90B3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyG0ZuZumMRQH98M2zOGMJ47pcDKedtQM',
    appId: '1:89201019839:android:64561ed5f4ccaeb968af0a',
    messagingSenderId: '89201019839',
    projectId: 'aaj-kya-banaye-5d8a4',
    storageBucket: 'aaj-kya-banaye-5d8a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA89eLcgUqQOvrntbO0zYNXz1N6T9cWnoE',
    appId: '1:89201019839:ios:dea11215dff29fb068af0a',
    messagingSenderId: '89201019839',
    projectId: 'aaj-kya-banaye-5d8a4',
    storageBucket: 'aaj-kya-banaye-5d8a4.appspot.com',
    androidClientId: '89201019839-q84rtii2ohtjanrppsck1155k7n4kb1j.apps.googleusercontent.com',
    iosClientId: '89201019839-15893lhsqot7m9iunue415u1md859mqr.apps.googleusercontent.com',
    iosBundleId: 'com.example.aajKyaBanayeAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA89eLcgUqQOvrntbO0zYNXz1N6T9cWnoE',
    appId: '1:89201019839:ios:96fc260f70386c1d68af0a',
    messagingSenderId: '89201019839',
    projectId: 'aaj-kya-banaye-5d8a4',
    storageBucket: 'aaj-kya-banaye-5d8a4.appspot.com',
    androidClientId: '89201019839-q84rtii2ohtjanrppsck1155k7n4kb1j.apps.googleusercontent.com',
    iosClientId: '89201019839-pq1nm69a97bknt3678htlgo9dk3tr6u6.apps.googleusercontent.com',
    iosBundleId: 'com.example.aajKyaBanayeAdmin.RunnerTests',
  );
}
